"""A very small HTML tree, built on the standard library's HTMLParser.

The original bot used BeautifulSoup. Dropping that dependency is what lets a
classmate run this with the python3 that is already on their machine, with no
pip, no virtualenv and no "externally-managed-environment" detour. pknuai's
markup is generated by a JSP and is regular enough that this handles it; the
parser is deliberately forgiving about unclosed tags because the page has a
few.
"""

from __future__ import annotations

import re
from html import unescape
from html.parser import HTMLParser

VOID_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}
# Tags the page opens without ever closing. A new one of the same kind (or the
# end of its parent) closes the previous one, the way a browser does.
SELF_CLOSING_SIBLINGS = {"p", "li", "option", "td", "th", "tr", "dt", "dd"}
# A block element starting inside an unclosed <p> ends it, as in a browser.
BLOCK_TAGS = {
    "address", "article", "aside", "blockquote", "div", "dl", "fieldset",
    "footer", "form", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hr",
    "main", "nav", "ol", "p", "pre", "section", "table", "ul",
}


class Node:
    """One element. Text lives in ``.texts`` interleaved with children order."""

    __slots__ = ("tag", "attrs", "children", "parent", "_text_parts")

    def __init__(self, tag: str, attrs=None, parent=None):
        self.tag = tag
        self.attrs = dict(attrs or {})
        self.children: list = []
        self.parent = parent
        self._text_parts: list = []

    # -- reading -------------------------------------------------------
    def get(self, name: str, default: str = "") -> str:
        value = self.attrs.get(name)
        return default if value is None else str(value)

    def classes(self) -> list:
        return self.get("class").split()

    def has_class(self, name: str) -> bool:
        return name in self.classes()

    def text(self, separator: str = " ") -> str:
        """All text under this element, whitespace collapsed."""
        parts: list = []
        stack = [self]
        while stack:
            node = stack.pop(0)
            parts.extend(node._text_parts)
            stack = list(node.children) + stack
        joined = separator.join(part for part in parts if part)
        return re.sub(r"\s+", " ", joined).strip()

    def iter(self):
        """This element and every descendant, in document order."""
        yield self
        for child in self.children:
            for node in child.iter():
                yield node

    def find_all(self, tag: str = "", *, cls: str = "", attr: str = "", limit: int = 0) -> list:
        found = []
        for node in self.iter():
            if node is self:
                continue
            if tag and node.tag != tag:
                continue
            if cls and not node.has_class(cls):
                continue
            if attr and attr not in node.attrs:
                continue
            found.append(node)
            if limit and len(found) >= limit:
                break
        return found

    def find(self, tag: str = "", *, cls: str = "", attr: str = ""):
        found = self.find_all(tag, cls=cls, attr=attr, limit=1)
        return found[0] if found else None

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<Node {self.tag} {self.attrs} children={len(self.children)}>"


class _TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node("[document]")
        self._stack = [self.root]

    def _current(self) -> Node:
        return self._stack[-1]

    def handle_starttag(self, tag, attrs):
        if tag in SELF_CLOSING_SIBLINGS and self._current().tag == tag:
            self._stack.pop()
        elif tag in BLOCK_TAGS and self._current().tag == "p":
            self._stack.pop()
        node = Node(tag, dict(attrs), self._current())
        self._current().children.append(node)
        if tag not in VOID_TAGS:
            self._stack.append(node)

    def handle_startendtag(self, tag, attrs):
        node = Node(tag, dict(attrs), self._current())
        self._current().children.append(node)

    def handle_endtag(self, tag):
        # Close the nearest matching ancestor; a stray </div> that matches
        # nothing is ignored rather than unwinding the whole document.
        for depth in range(len(self._stack) - 1, 0, -1):
            if self._stack[depth].tag == tag:
                del self._stack[depth:]
                return

    def handle_data(self, data):
        if data and data.strip():
            self._current()._text_parts.append(data.strip())


def parse(html_text: str) -> Node:
    builder = _TreeBuilder()
    try:
        builder.feed(html_text or "")
        builder.close()
    except Exception:  # noqa: BLE001 - a broken page must not raise here
        pass
    return builder.root


def strip_tags(html_text: str) -> str:
    """The page's visible text, entities decoded, whitespace collapsed.

    pknuai prints the recruiting window with ``&nbsp;`` between the date and
    the time. Removing the tags leaves those entities behind as literal text,
    which is enough to hide the published minute from a regular expression —
    that bug once let the bot read a 09:00 opening as midnight and never see
    the closing date at all. Decode before matching, always.
    """
    return re.sub(r"\s+", " ", unescape(re.sub(r"<[^>]+>", " ", html_text or ""))).strip()
